### ISSUE TITLE
NeutrinoCalculator cannot handle a list of sources with different minimum and maximum energies

### ISSUE THREAD

**Issue by lenasaurenhaus** [cescalara/icecube_tools#30]
When passing a list of sources with different `min_energy` and `max_energy` to `NeutrinoCalculator`, the calculated number of neutrino events for each source seems to depend on the order of the sources in the list. This is probably because the effective area used to calculate the number of neutrino events is reused for every source after it is set to zero outside of the energy interval `[min_energy, max_energy]` on which the first source in the list of sources is defined.

**Comment by cescalara** [comment]
Fixed by https://github.com/cescalara/icecube_tools/pull/31 :)
