### ISSUE TITLE
Violation of GPL license

### ISSUE THREAD

**Issue by grburgess** [cescalara/icecube_tools#41]
Recently it came to my attention that part of popsynth was copied without my knowledge into this software:
https://github.com/cescalara/icecube_tools/blob/master/icecube_tools/utils/bpl_sampling.py

While it is odd given that I was not asked and it was related to a private conversation on how to more efficiently sample effective areas (which will be handled in a separate issue), it still violates the GPL license under which popsynth resides as it attempts to relicense the code with an MIT license. I have not given permission for the relicense and there are rather strict rules for the redistribution of  GPL code under a new license. 

I would appreciate ceasing to distribute this code under the MIT license and either relicense it under GPL by following the appropriate documenting, archiving, and separation procedures or whatever is required to be compliant.

I think in the future it is better to discuss, especially with collaborators, before simply lifting their code from their repositories since this defeats the spirit of open source code.

**Comment by cescalara** [comment]
Thank you for highlighting this issue. The code is copied from https://github.com/grburgess/brokenpl_sample, not popsynth, as mentioned in the comments. I read through the GPLv3 text, and it should be sufficient to update the licence, as done in #42.  If you would prefer, we can look for a package to handle the broken power law sampling or implement it from scratch; we would prefer to reuse code and give credit where possible.

I recall discussing with you the appropriate reuse of this code when I originally used the brokenpl_sample code some ~3 years after you shared it in a Facebook group. I apologize for not checking in again this time.

**Comment by grburgess** [comment]
I think it might be easier for me to make some PRs deleting the copied / non-attributed code in order to not put the burden on the developers. It's dispersed throughout different regions. However, it would be great if my code could stop being distributed with the wrong license sooner than later.

**Comment by cescalara** [comment]
While I am happy to update the licence as suggested in this issue (and have done so), I strongly disagree with the unsubstantiated and vague claims of plagiarism made here as well as in issue #43, and PRs #44 and #45. The PRs would break the software and it seems the intention is not constructive. I will close these issues and PRs. Please do not continue to continue to open such issues and pull requests on my repositories.

**Comment by grburgess** [comment]
I'm happy to provide precise details. The intention has been to be be constructive but has been ignored. I will reopen until they are addressed. Dismissing comments of plagiarism is not unilateral. I'm happy to discuss this.
